import DOMPurify from 'dompurify';

export const sanitizeMessage = (html: string): string => {
  return DOMPurify.sanitize(html, {
    // Only allow the most basic formatting tags
    ALLOWED_TAGS: ['p', 'strong', 'em', 'b', 'i', 'ul', 'ol', 'li', 'br'],

    // Remove href and target attributes to prevent link-based attacks
    ALLOWED_ATTR: [],

    // Disallow unknown protocols
    ALLOW_UNKNOWN_PROTOCOLS: false,

    // Only allow https and http protocols (removed mailto)
    ALLOWED_URI_REGEXP: /^https?:\/\//i,

    // Forbid all potentially dangerous tags
    FORBID_TAGS: [
      'style',
      'script',
      'iframe',
      'form',
      'input',
      'button',
      'select',
      'textarea',
      'noscript',
      'embed',
      'object',
      'base',
      'link',
      'a', // Remove links entirely for maximum security
      'img', // Remove images to prevent potential issues
      'video',
      'audio',
      'canvas',
      'svg',
      'math',
      'details',
      'summary',
      'dialog',
      'menu',
      'menuitem',
      'template',
      'slot',
      'picture',
      'source',
      'track',
      'map',
      'area',
      'applet',
      'bgsound',
      'command',
      'datalist',
      'fieldset',
      'keygen',
      'legend',
      'optgroup',
      'option',
      'output',
      'progress',
      'meter',
      'time',
      'mark',
      'ruby',
      'rt',
      'rp',
      'bdi',
      'bdo',
      'wbr',
      's',
      'strike',
      'tt',
      'big',
      'small',
      'center',
      'font',
      'u', // Remove underline as it's not essential
    ],

    // Forbid all potentially dangerous attributes
    FORBID_ATTR: [
      'style',
      'on*', // All event handlers
      'background',
      'srcset',
      'formaction',
      'form',
      'xlink:href',
      'href', // Remove href entirely
      'target', // Remove target entirely
      'rel',
      'id',
      'class',
      'data-*', // Remove all data attributes
      'aria-*', // Remove all ARIA attributes
      'role',
      'tabindex',
      'contenteditable',
      'draggable',
      'dropzone',
      'hidden',
      'spellcheck',
      'translate',
      'autocapitalize',
      'autocomplete',
      'autocorrect',
      'autofocus',
      'autosave',
      'checked',
      'disabled',
      'formnovalidate',
      'multiple',
      'novalidate',
      'readonly',
      'required',
      'selected',
      'value',
      'maxlength',
      'minlength',
      'pattern',
      'placeholder',
      'size',
      'step',
      'min',
      'max',
      'width',
      'height',
      'alt',
      'title',
      'lang',
      'dir',
      'accesskey',
      'contextmenu',
      'download',
      'hreflang',
      'media',
      'ping',
      'referrerpolicy',
      'type',
      'usemap',
      'shape',
      'coords',
      'ismap',
      'longdesc',
      'name',
      'sizes',
      'src',
      'crossorigin',
      'integrity',
      'referrerpolicy',
      'sandbox',
      'srcdoc',
      'allowfullscreen',
      'allowpaymentrequest',
      'allowusermedia',
      'loading',
      'decoding',
      'fetchpriority',
      'importance',
      'lazyload',
      'preload',
      'poster',
      'preload',
      'autoplay',
      'controls',
      'loop',
      'muted',
      'playsinline',
      'default',
      'kind',
      'label',
      'srclang',
      'challenge',
      'keytype',
      'cite',
      'datetime',
      'pubdate',
      'reversed',
      'start',
      'compact',
      'declare',
      'standby',
      'valuetype',
      'archive',
      'classid',
      'codebase',
      'codetype',
      'data',
      'declare',
      'standby',
      'valuetype',
      'archive',
      'classid',
      'codebase',
      'codetype',
      'data',
      'declare',
      'standby',
      'valuetype',
    ],
  });
};
