export const CREATE_EDIT_CODEBASE_DIALOG_NAME = 'CREATE_EDIT_CODEBASE_DIALOG';
export const FORM_PART_CODEBASE_INFO = 'FORM_PART_CODEBASE_INFO';
export const FORM_PART_ADVANCED_SETTINGS = 'FORM_PART_ADVANCED_SETTINGS';

export const TAB_INDEXES = {
  [FORM_PART_CODEBASE_INFO]: 0,
  [FORM_PART_ADVANCED_SETTINGS]: 1,
};
