export const CODEBASE_COMMON_LANGUAGES = {
  JAVA: 'java',
  JAVASCRIPT: 'javascript',
  PYTHON: 'python',
  GROOVY_PIPELINE: 'groovy-pipeline',
  HCL: 'hcl',
  REGO: 'rego',
  CONTAINER: 'container',
  HELM: 'helm',
  GO: 'go',
  C_SHARP: 'csharp',
  C: 'c',
  CPP: 'cpp',
  OTHER: 'other',
} as const;

export const CODEBASE_COMMON_FRAMEWORKS = {
  JAVA17: 'java17',
  JAVA21: 'java21',
  JAVA25: 'java25',
  REACT: 'react',
  VUE: 'vue',
  NEXTJS: 'next',
  ANTORA: 'antora',
  EXPRESS: 'express',
  ANGULAR: 'angular',
  CODENARC: 'codenarc',
  TERRAFORM: 'terraform',
  OPA: 'opa',
  DOCKER: 'docker',
  PIPELINE: 'pipeline',
  BEEGO: 'beego',
  FLASK: 'flask',
  HELM: 'helm',
  CHARTS: 'charts',
  FASTAPI: 'fastapi',
  DOTNET_3_1: 'dotnet-3.1',
  DOTNET_6_0: 'dotnet-6.0',
  PYTHON_3_8: 'python-3.8',
  OPERATOR_SDK: 'operator-sdk',
  GIN: 'gin',
  AWS: 'aws',
  GIT_OPS: 'gitops',
  ANSIBLE: 'ansible',
  NONE: 'none',
} as const;

export const CODEBASE_COMMON_BUILD_TOOLS = {
  GRADLE: 'gradle',
  MAVEN: 'maven',
  NPM: 'npm',
  DOTNET: 'dotnet',
  GO: 'go',
  PYTHON: 'python',
  CODENARC: 'codenarc',
  TERRAFORM: 'terraform',
  OPA: 'opa',
  KANIKO: 'kaniko',
  HELM: 'helm',
  MAKE: 'make',
  C_MAKE: 'cmake',
  PNPM: 'pnpm',
} as const;
