export const CODEBASE_COMMON_LANGUAGES = {
    JAVA: 'java',
    JAVASCRIPT: 'javascript',
    DOTNET: 'dotnet',
    PYTHON: 'python',
    GROOVY_PIPELINE: 'groovy-pipeline',
    TERRAFORM: 'terraform',
    REGO: 'rego',
    CONTAINER: 'container',
    HELM: 'helm',
    GO: 'go',
    C_SHARP: 'csharp',
    OTHER: 'other',
} as const;

export const CODEBASE_COMMON_FRAMEWORKS = {
    JAVA8: 'java8',
    JAVA11: 'java11',
    JAVA17: 'java17',
    REACT: 'react',
    VUE: 'vue',
    EXPRESS: 'express',
    ANGULAR: 'angular',
    CODENARC: 'codenarc',
    TERRAFORM: 'terraform',
    OPA: 'opa',
    DOCKER: 'docker',
    PIPELINE: 'pipeline',
    BEEGO: 'beego',
    FLASK: 'flask',
    FASTAPI: 'fastapi',
    DOTNET_3_1: 'dotnet-3.1',
    DOTNET_6_0: 'dotnet-6.0',
    PYTHON_3_8: 'python-3.8',
    OPERATOR_SDK: 'operator-sdk',
} as const;

export const CODEBASE_COMMON_BUILD_TOOLS = {
    GRADLE: 'gradle',
    MAVEN: 'maven',
    NPM: 'npm',
    DOTNET: 'dotnet',
    GO: 'go',
    PYTHON: 'python',
    CODENARC: 'codenarc',
    TERRAFORM: 'terraform',
    OPA: 'opa',
    KANIKO: 'kaniko',
    HELM: 'helm',
} as const;
