export enum ICONS {
    PENCIL = 'ci:edit',
    PLUS = 'akar-icons:plus',
    DOCUMENT_ADD = 'carbon:document-add',
    ARROW_LEFT = 'eva:arrow-back-outline',
    THREE_DOTS = 'mi:options-vertical',
    ARROW_DOWN = 'dashicons:arrow-down-alt2',
    ROCKET = 'ion:rocket-outline',
    PANEL = 'material-symbols:view-quilt-outline-rounded',
    INFINITY = 'ion:infinite-outline',
    APPLICATION = 'fluent:app-generic-24-regular',
    TEST_APPLICATION = 'file-icons:test-generic',
    BOOKS = 'fluent:library-16-regular',
    BUCKET = 'mdi:delete',
    EMPTY_CIRCLE = 'akar-icons:circle',
    CHECK_CIRCLE = 'bi:check-circle',
    CROSS_CIRCLE = 'uiw:circle-close-o',
    LOADER_CIRCLE = 'lucide:loader-2',
    INFO_CIRCLE = 'ant-design:info-circle-outlined',
    REPOSITORY = 'mdi:source-repository-multiple',
    INFO = 'fe:info',
}
