export const REQUEST_KEY_QUERY_TRIGGER_TEMPLATE_LIST = 'REQUEST_KEY_QUERY_TRIGGER_TEMPLATE_LIST';
export const REQUEST_KEY_QUERY_TRIGGER_TEMPLATE_LIST_BY_TYPE =
  'REQUEST_KEY_QUERY_TRIGGER_TEMPLATE_LIST_BY_TYPE';
export const REQUEST_KEY_QUERY_TRIGGER_TEMPLATE_BY_NAME =
  'REQUEST_KEY_QUERY_TRIGGER_TEMPLATE_BY_NAME';
