export const CREATE_EDIT_CD_PIPELINE_DIALOG_NAME = 'CREATE_EDIT_CD_PIPELINE_DIALOG';

export const FORM_PART_PIPELINE = 'FORM_PART_PIPELINE';
export const FORM_PART_APPLICATIONS = 'FORM_PART_APPLICATIONS';
export const FORM_PART_STAGES = 'FORM_PART_STAGES';

export const TAB_INDEXES = {
    [FORM_PART_PIPELINE]: 0,
    [FORM_PART_APPLICATIONS]: 1,
    [FORM_PART_STAGES]: 2,
};
