import { FormNameObject } from '../../../../types/forms';
import {
    CODEBASE_CREATION_NAME_ADVANCED_MAPPING_FIELD_NAME,
    CODEBASE_CREATION_NAME_ADVANCED_MAPPING_JIRA_PATTERN,
    CODEBASE_CREATION_NAME_API_VERSION,
    CODEBASE_CREATION_NAME_BUILD_TOOL,
    CODEBASE_CREATION_NAME_CI_TOOL,
    CODEBASE_CREATION_NAME_COMMIT_MESSAGE_PATTERN,
    CODEBASE_CREATION_NAME_DEFAULT_BRANCH,
    CODEBASE_CREATION_NAME_DEPLOYMENT_SCRIPT,
    CODEBASE_CREATION_NAME_DESCRIPTION,
    CODEBASE_CREATION_NAME_EMPTY_PROJECT,
    CODEBASE_CREATION_NAME_FRAMEWORK,
    CODEBASE_CREATION_NAME_GIT_SERVER,
    CODEBASE_CREATION_NAME_GIT_URL_PATH,
    CODEBASE_CREATION_NAME_HAS_CODEBASE_AUTH,
    CODEBASE_CREATION_NAME_HAS_JIRA_INTEGRATION,
    CODEBASE_CREATION_NAME_JENKINS_SLAVE,
    CODEBASE_CREATION_NAME_JIRA_ISSUE_METADATA_PAYLOAD,
    CODEBASE_CREATION_NAME_JIRA_SERVER,
    CODEBASE_CREATION_NAME_JOB_PROVISIONING,
    CODEBASE_CREATION_NAME_KIND,
    CODEBASE_CREATION_NAME_LANG,
    CODEBASE_CREATION_NAME_NAME,
    CODEBASE_CREATION_NAME_NAMESPACE,
    CODEBASE_CREATION_NAME_REPOSITORY_LOGIN,
    CODEBASE_CREATION_NAME_REPOSITORY_PASSWORD_OR_API_TOKEN,
    CODEBASE_CREATION_NAME_REPOSITORY_URL,
    CODEBASE_CREATION_NAME_STRATEGY,
    CODEBASE_CREATION_NAME_TEST_REPORT_FRAMEWORK,
    CODEBASE_CREATION_NAME_TICKET_NAME_PATTERN,
    CODEBASE_CREATION_NAME_TYPE,
    CODEBASE_CREATION_NAME_VERSIONING_START_FROM,
    CODEBASE_CREATION_NAME_VERSIONING_START_FROM_SNAPSHOT,
    CODEBASE_CREATION_NAME_VERSIONING_START_FROM_VERSION,
    CODEBASE_CREATION_NAME_VERSIONING_TYPE,
    FORM_PART_ADVANCED_SETTINGS,
    FORM_PART_CODEBASE_INFO,
    FORM_PART_CODEBASE_TYPE_INFO,
} from '../../constants';

export const APPLICATION_NAMES: { [key: string]: FormNameObject } = {
    // NOT USED IN FORM DATA
    apiVersion: CODEBASE_CREATION_NAME_API_VERSION,
    kind: CODEBASE_CREATION_NAME_KIND,
    hasCodebaseAuth: CODEBASE_CREATION_NAME_HAS_CODEBASE_AUTH,
    repositoryLogin: CODEBASE_CREATION_NAME_REPOSITORY_LOGIN,
    repositoryPasswordOrApiToken: CODEBASE_CREATION_NAME_REPOSITORY_PASSWORD_OR_API_TOKEN,
    hasJiraServerIntegration: CODEBASE_CREATION_NAME_HAS_JIRA_INTEGRATION,
    versioningStartFromVersion: CODEBASE_CREATION_NAME_VERSIONING_START_FROM_VERSION,
    versioningStartFromSnapshot: CODEBASE_CREATION_NAME_VERSIONING_START_FROM_SNAPSHOT,
    advancedMappingFieldName: CODEBASE_CREATION_NAME_ADVANCED_MAPPING_FIELD_NAME,
    advancedMappingJiraPattern: CODEBASE_CREATION_NAME_ADVANCED_MAPPING_JIRA_PATTERN,

    // FORM PART CODEBASE INFO
    type: CODEBASE_CREATION_NAME_TYPE,
    namespace: CODEBASE_CREATION_NAME_NAMESPACE,
    strategy: CODEBASE_CREATION_NAME_STRATEGY,
    repositoryUrl: CODEBASE_CREATION_NAME_REPOSITORY_URL,
    gitServer: CODEBASE_CREATION_NAME_GIT_SERVER,
    gitUrlPath: CODEBASE_CREATION_NAME_GIT_URL_PATH,

    // FORM PART APPLICATION INFO
    name: CODEBASE_CREATION_NAME_NAME,
    defaultBranch: CODEBASE_CREATION_NAME_DEFAULT_BRANCH,
    emptyProject: CODEBASE_CREATION_NAME_EMPTY_PROJECT,
    lang: CODEBASE_CREATION_NAME_LANG,
    framework: CODEBASE_CREATION_NAME_FRAMEWORK,
    buildTool: CODEBASE_CREATION_NAME_BUILD_TOOL,

    // FORM PART ADVANCED SETTINGS
    jobProvisioning: CODEBASE_CREATION_NAME_JOB_PROVISIONING,
    jenkinsSlave: CODEBASE_CREATION_NAME_JENKINS_SLAVE,
    versioningType: CODEBASE_CREATION_NAME_VERSIONING_TYPE,
    versioningStartFrom: CODEBASE_CREATION_NAME_VERSIONING_START_FROM,
    deploymentScript: CODEBASE_CREATION_NAME_DEPLOYMENT_SCRIPT,
    ciTool: CODEBASE_CREATION_NAME_CI_TOOL,
    jiraServer: CODEBASE_CREATION_NAME_JIRA_SERVER,
    commitMessagePattern: CODEBASE_CREATION_NAME_COMMIT_MESSAGE_PATTERN,
    ticketNamePattern: CODEBASE_CREATION_NAME_TICKET_NAME_PATTERN,
    jiraIssueMetadataPayload: CODEBASE_CREATION_NAME_JIRA_ISSUE_METADATA_PAYLOAD,
};

export const LIBRARY_NAMES: { [key: string]: FormNameObject } = {
    // NOT USED IN FORM DATA
    apiVersion: CODEBASE_CREATION_NAME_API_VERSION,
    kind: CODEBASE_CREATION_NAME_KIND,
    hasCodebaseAuth: CODEBASE_CREATION_NAME_HAS_CODEBASE_AUTH,
    repositoryLogin: CODEBASE_CREATION_NAME_REPOSITORY_LOGIN,
    repositoryPasswordOrApiToken: CODEBASE_CREATION_NAME_REPOSITORY_PASSWORD_OR_API_TOKEN,
    hasJiraServerIntegration: CODEBASE_CREATION_NAME_HAS_JIRA_INTEGRATION,
    versioningStartFromVersion: CODEBASE_CREATION_NAME_VERSIONING_START_FROM_VERSION,
    versioningStartFromSnapshot: CODEBASE_CREATION_NAME_VERSIONING_START_FROM_SNAPSHOT,
    advancedMappingFieldName: CODEBASE_CREATION_NAME_ADVANCED_MAPPING_FIELD_NAME,
    advancedMappingJiraPattern: CODEBASE_CREATION_NAME_ADVANCED_MAPPING_JIRA_PATTERN,

    // FORM PART CODEBASE INFO
    type: CODEBASE_CREATION_NAME_TYPE,
    namespace: CODEBASE_CREATION_NAME_NAMESPACE,
    strategy: CODEBASE_CREATION_NAME_STRATEGY,
    repositoryUrl: CODEBASE_CREATION_NAME_REPOSITORY_URL,
    gitServer: CODEBASE_CREATION_NAME_GIT_SERVER,
    gitUrlPath: CODEBASE_CREATION_NAME_GIT_URL_PATH,

    // FORM PART LIBRARY INFO
    name: CODEBASE_CREATION_NAME_NAME,
    defaultBranch: CODEBASE_CREATION_NAME_DEFAULT_BRANCH,
    emptyProject: CODEBASE_CREATION_NAME_EMPTY_PROJECT,
    lang: CODEBASE_CREATION_NAME_LANG,
    framework: CODEBASE_CREATION_NAME_FRAMEWORK,
    buildTool: CODEBASE_CREATION_NAME_BUILD_TOOL,

    // FORM PART ADVANCED SETTINGS
    jobProvisioning: CODEBASE_CREATION_NAME_JOB_PROVISIONING,
    jenkinsSlave: CODEBASE_CREATION_NAME_JENKINS_SLAVE,
    versioningType: CODEBASE_CREATION_NAME_VERSIONING_TYPE,
    versioningStartFrom: CODEBASE_CREATION_NAME_VERSIONING_START_FROM,
    deploymentScript: CODEBASE_CREATION_NAME_DEPLOYMENT_SCRIPT,
    ciTool: CODEBASE_CREATION_NAME_CI_TOOL,
    jiraServer: CODEBASE_CREATION_NAME_JIRA_SERVER,
    commitMessagePattern: CODEBASE_CREATION_NAME_COMMIT_MESSAGE_PATTERN,
    ticketNamePattern: CODEBASE_CREATION_NAME_TICKET_NAME_PATTERN,
    jiraIssueMetadataPayload: CODEBASE_CREATION_NAME_JIRA_ISSUE_METADATA_PAYLOAD,
};

export const AUTOTEST_NAMES: { [key: string]: FormNameObject } = {
    // NOT USED IN FORM DATA
    apiVersion: CODEBASE_CREATION_NAME_API_VERSION,
    kind: CODEBASE_CREATION_NAME_KIND,
    hasCodebaseAuth: CODEBASE_CREATION_NAME_HAS_CODEBASE_AUTH,
    repositoryLogin: CODEBASE_CREATION_NAME_REPOSITORY_LOGIN,
    repositoryPasswordOrApiToken: CODEBASE_CREATION_NAME_REPOSITORY_PASSWORD_OR_API_TOKEN,
    hasJiraServerIntegration: CODEBASE_CREATION_NAME_HAS_JIRA_INTEGRATION,
    versioningStartFromVersion: CODEBASE_CREATION_NAME_VERSIONING_START_FROM_VERSION,
    versioningStartFromSnapshot: CODEBASE_CREATION_NAME_VERSIONING_START_FROM_SNAPSHOT,
    advancedMappingFieldName: CODEBASE_CREATION_NAME_ADVANCED_MAPPING_FIELD_NAME,
    advancedMappingJiraPattern: CODEBASE_CREATION_NAME_ADVANCED_MAPPING_JIRA_PATTERN,

    // FORM PART CODEBASE INFO
    type: CODEBASE_CREATION_NAME_TYPE,
    namespace: CODEBASE_CREATION_NAME_NAMESPACE,
    strategy: CODEBASE_CREATION_NAME_STRATEGY,
    repositoryUrl: CODEBASE_CREATION_NAME_REPOSITORY_URL,
    gitServer: CODEBASE_CREATION_NAME_GIT_SERVER,
    gitUrlPath: CODEBASE_CREATION_NAME_GIT_URL_PATH,
    emptyProject: CODEBASE_CREATION_NAME_EMPTY_PROJECT,

    // FORM PART AUTOTEST INFO
    name: CODEBASE_CREATION_NAME_NAME,
    description: CODEBASE_CREATION_NAME_DESCRIPTION,
    defaultBranch: CODEBASE_CREATION_NAME_DEFAULT_BRANCH,
    lang: CODEBASE_CREATION_NAME_LANG,
    framework: CODEBASE_CREATION_NAME_FRAMEWORK,
    buildTool: CODEBASE_CREATION_NAME_BUILD_TOOL,
    testReportFramework: CODEBASE_CREATION_NAME_TEST_REPORT_FRAMEWORK,

    // FORM PART ADVANCED SETTINGS
    jobProvisioning: CODEBASE_CREATION_NAME_JOB_PROVISIONING,
    jenkinsSlave: CODEBASE_CREATION_NAME_JENKINS_SLAVE,
    versioningType: CODEBASE_CREATION_NAME_VERSIONING_TYPE,
    versioningStartFrom: CODEBASE_CREATION_NAME_VERSIONING_START_FROM,
    ciTool: CODEBASE_CREATION_NAME_CI_TOOL,
    jiraServer: CODEBASE_CREATION_NAME_JIRA_SERVER,
    commitMessagePattern: CODEBASE_CREATION_NAME_COMMIT_MESSAGE_PATTERN,
    ticketNamePattern: CODEBASE_CREATION_NAME_TICKET_NAME_PATTERN,
    jiraIssueMetadataPayload: CODEBASE_CREATION_NAME_JIRA_ISSUE_METADATA_PAYLOAD,
};

export const TAB_INDEXES = {
    [FORM_PART_CODEBASE_INFO]: 0,
    [FORM_PART_CODEBASE_TYPE_INFO]: 1,
    [FORM_PART_ADVANCED_SETTINGS]: 2,
};
