export const FORM_PART_CODEBASE_INFO = 'FORM_PART_CODEBASE_INFO';
export const FORM_PART_CODEBASE_TYPE_INFO = 'FORM_PART_CODEBASE_TYPE_INFO';
export const FORM_PART_ADVANCED_SETTINGS = 'FORM_PART_ADVANCED_SETTINGS';

export const TAB_INDEXES = {
    [FORM_PART_CODEBASE_INFO]: 0,
    [FORM_PART_CODEBASE_TYPE_INFO]: 1,
    [FORM_PART_ADVANCED_SETTINGS]: 2,
};
