{{- if eq .Values.global.platform "openshift" -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "headlamp.name" . }}
  labels:
    {{- include "headlamp.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
    host: portal-{{ .Release.Namespace }}.{{ .Values.global.dnsWildCard }}
    tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
    to:
        kind: Service
        name: {{ include "headlamp.name" . }}
        weight: 100
    wildcardPolicy: None
{{- end -}}
