import { GIT_PROVIDER } from '../../../constants/gitProviders';
import { GitURLService } from './index';

describe('testing link-creation GitURLService', () => {
  it('should successfully create git ops value file url  based on given gitOpsWebUrl, pipeline name,  stage name, app name and git server params', () => {
    expect(
      GitURLService.createGitOpsValuesYamlFileLink(
        'https://git.test.com/test-project/test-env/krci-gitops',
        'test-pipeline-name',
        'test-stage-name',
        'test-app-name',
        GIT_PROVIDER.GITHUB
      )
    ).toEqual(
      'https://git.test.com/test-project/test-env/krci-gitops/blob/main/test-pipeline-name/test-stage-name/test-app-name-values.yaml'
    );
    expect(
      GitURLService.createGitOpsValuesYamlFileLink(
        'https://git.test.com/test-project/test-env/krci-gitops',
        'test-pipeline-name',
        'test-stage-name',
        'test-app-name',
        GIT_PROVIDER.GITLAB
      )
    ).toEqual(
      'https://git.test.com/test-project/test-env/krci-gitops/blob/main/test-pipeline-name/test-stage-name/test-app-name-values.yaml'
    );
    expect(
      GitURLService.createGitOpsValuesYamlFileLink(
        'https://test-gerrit.com/gitweb?p=krci-gitops.git',
        'test-pipeline-name',
        'test-stage-name',
        'test-app-name',
        GIT_PROVIDER.GERRIT
      )
    ).toEqual(
      'https://test-gerrit.com/gitweb?p=krci-gitops.git&f=test-pipeline-name%2Ftest-stage-name%2Ftest-app-name-values.yaml&hb=refs%2Fheads%2Fmain&a=blob'
    );
    expect(
      GitURLService.createGitOpsValuesYamlFileLink(
        'https://git.test.com/test-project/test-env/krci-gitops',
        'test-pipeline-name',
        'test-stage-name',
        'test-app-name',
        GIT_PROVIDER.BITBUCKET
      )
    ).toEqual(
      'https://git.test.com/test-project/test-env/krci-gitops/src/main/test-pipeline-name/test-stage-name/test-app-name-values.yaml'
    );
  });

  it('should successfully create repo branch link based on given git server, baseUrl, and branch', () => {
    expect(
      GitURLService.createRepoBranchLink(
        GIT_PROVIDER.GITHUB,
        'https://git.test.com/test-project/test-repo',
        'test-branch'
      )
    ).toEqual('https://git.test.com/test-project/test-repo/tree/test-branch');
    expect(
      GitURLService.createRepoBranchLink(
        GIT_PROVIDER.GITLAB,
        'https://git.test.com/test-project/test-repo',
        'test-branch'
      )
    ).toEqual('https://git.test.com/test-project/test-repo/-/tree/test-branch');
    expect(
      GitURLService.createRepoBranchLink(
        GIT_PROVIDER.GERRIT,
        'https://test-gerrit.com/gitweb?p=test-repo',
        'test-branch'
      )
    ).toEqual('https://test-gerrit.com/gitweb?p=test-repo&a=tree&h=refs%2Fheads%2Ftest-branch');
    expect(
      GitURLService.createRepoBranchLink(
        GIT_PROVIDER.BITBUCKET,
        'https://git.test.com/test-project/test-repo',
        'feature/test-branch'
      )
    ).toEqual('https://git.test.com/test-project/test-repo/src/HEAD/?at=feature%2Ftest-branch');
  });
});
